using System.Collections.Generic;
using UnityEngine;

namespace Darkroom
{
    /// Procedural pixel art — sprites authored as string maps, world tiles
    /// generated by rule. Still zero external assets.
    public static class PixelArt
    {
        /// rows are listed top to bottom; '.' = transparent.
        public static Sprite FromMap(string name, string[] rows, Dictionary<char, Color32> palette, float ppu)
        {
            int h = rows.Length, w = rows[0].Length;
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
            tex.filterMode = FilterMode.Bilinear;
            var px = new Color32[w * h];
            for (int y = 0; y < h; y++)
                for (int x = 0; x < w; x++)
                {
                    char c = rows[y][x];
                    px[(h - 1 - y) * w + x] = c == '.' ? new Color32(0, 0, 0, 0) : palette[c];
                }
            tex.SetPixels32(px);
            tex.Apply();
            var s = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 0.5f), ppu, 0, SpriteMeshType.FullRect);
            s.name = name;
            return s;
        }

        static Sprite MakeTile(string name, int size, float ppu, System.Func<int, int, Color32> pixel)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            tex.filterMode = FilterMode.Bilinear;
            tex.wrapMode = TextureWrapMode.Repeat;
            var px = new Color32[size * size];
            for (int y = 0; y < size; y++)
                for (int x = 0; x < size; x++)
                    px[y * size + x] = pixel(x, y);
            tex.SetPixels32(px);
            tex.Apply();
            var s = Sprite.Create(tex, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), ppu, 0, SpriteMeshType.FullRect);
            s.name = name;
            return s;
        }

        static Color32 C(int rgb) =>
            new Color32((byte)((rgb >> 16) & 0xFF), (byte)((rgb >> 8) & 0xFF), (byte)(rgb & 0xFF), 255);

        // ---------- noise ----------

        internal static float Hash(int x, int y, int s)
        {
            unchecked
            {
                int h = x * 374761393 + y * 668265263 + s * 1442695041;
                h = (h ^ (h >> 13)) * 1274126177;
                return ((h ^ (h >> 16)) & 0x7FFFFFFF) / (float)int.MaxValue;
            }
        }

        internal static float ValueNoise(float x, float y, int seed)
        {
            int x0 = Mathf.FloorToInt(x), y0 = Mathf.FloorToInt(y);
            float fx = x - x0, fy = y - y0;
            float a = Hash(x0, y0, seed), b = Hash(x0 + 1, y0, seed);
            float c = Hash(x0, y0 + 1, seed), d = Hash(x0 + 1, y0 + 1, seed);
            return Mathf.Lerp(Mathf.Lerp(a, b, fx), Mathf.Lerp(c, d, fx), fy);
        }

        // ---------- world tiles ----------

        static Sprite _ground, _darkPath, _barrier, _door;
        static Sprite _concrete, _wall, _lightCone, _coneShade;

        /// Photo/illustration texture from StreamingAssets (CC0/authored, see README credits).
        /// Returns null when the file is missing — callers fall back to procedural.
        static Sprite LoadExternal(string file, float ppu) => LoadExternal(file, ppu, new Vector2(0.5f, 0.5f));

        /// Public single-art loader for one-off props (e.g. the prologue safelight
        /// fixture). StreamingAssets-relative path; null if absent (caller falls back).
        public static Sprite Art(string file, float ppu) => LoadExternal(file, ppu);

        static Sprite LoadExternal(string file, float ppu, Vector2 pivot)
        {
            try
            {
                string p = System.IO.Path.Combine(Application.streamingAssetsPath, file);
                if (!System.IO.File.Exists(p)) return null;
                var tex = new Texture2D(2, 2, TextureFormat.RGBA32, false);
                if (!tex.LoadImage(System.IO.File.ReadAllBytes(p))) return null;
                tex.wrapMode = TextureWrapMode.Repeat; // tiled walls need it; moot for feathered scenes/cutouts
                tex.filterMode = FilterMode.Bilinear;
                var s = Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height),
                    pivot, ppu, 0, SpriteMeshType.FullRect);
                s.name = file;
                return s;
            }
            catch { return null; }
        }

        /// Try each StreamingAssets-relative file in order; first that loads wins.
        /// Lets authored/AI art (art/…) override the legacy photo, which overrides procedural.
        static Sprite LoadExternalFirst(float ppu, params string[] files)
        {
            foreach (var f in files) { var s = LoadExternal(f, ppu); if (s != null) return s; }
            return null;
        }

        /// Concrete: cool dark authored wall (art/wall_concrete.png), legacy photo,
        /// then procedural noise. 512 ppu => one 1K tile spans 2 units.
        public static Sprite ConcreteTile
        {
            get
            {
                if (_concrete == null) _concrete = LoadExternalFirst(512f, "art/wall_concrete.png", "concrete.jpg");
                if (_concrete == null)
                    _concrete = MakeTile("ConcreteTile", 64, 64f, (x, y) =>
                    {
                        float n = ValueNoise(x / 8f, y / 8f, 11) * 0.6f + ValueNoise(x / 3f, y / 3f, 23) * 0.4f;
                        float v = 0.30f + n * 0.14f;
                        if (ValueNoise(x / 16f, y / 5f, 37) > 0.88f) v *= 0.7f; // grime streaks
                        byte g = (byte)(v * 255f);
                        return new Color32(g, g, (byte)Mathf.Min(255, g + 8), 255);
                    });
                return _concrete;
            }
        }

        /// Wall: cool dark plaster (art/wall_plaster.png). Replaces the old red-brick
        /// photo, which clashed with the monochrome darkroom palette. Legacy photo +
        /// neutral-grey procedural fallback kept so the game always renders.
        public static Sprite WallTile
        {
            get
            {
                if (_wall == null) _wall = LoadExternalFirst(512f, "art/wall_plaster.png", "bricks.jpg");
                if (_wall == null)
                    _wall = MakeTile("WallTile", 64, 64f, (x, y) =>
                    {
                        // neutral-grey ashlar fallback (no red): subtle blocks + speckle
                        int row = y / 16;
                        int xo = (row % 2) * 16;
                        bool mortar = (y % 16) < 2 || ((x + xo) % 32) < 2;
                        if (mortar) return new Color32(0x18, 0x18, 0x1C, 255);
                        float n = ValueNoise(x / 5f, y / 5f, 51);
                        byte g = (byte)((0.22f + n * 0.08f) * 255f);
                        return new Color32(g, g, (byte)Mathf.Min(255, g + 6), 255);
                    });
                return _wall;
            }
        }

        /// Authored/AI illustrated backdrop scenes — every `art/bd_*.png` in
        /// StreamingAssets, loaded at `ppu` (cached). Empty list when none exist, so
        /// the backdrop builder degrades gracefully. Drop a new bd_*.png in and it
        /// is picked up automatically on the next level build — no code change.
        static List<Sprite> _scenes;
        public static List<Sprite> BackdropScenes(float ppu)
        {
            if (_scenes != null) return _scenes;
            _scenes = new List<Sprite>();
            try
            {
                string dir = System.IO.Path.Combine(Application.streamingAssetsPath, "art");
                if (System.IO.Directory.Exists(dir))
                {
                    var files = System.IO.Directory.GetFiles(dir, "bd_*.png");
                    System.Array.Sort(files); // deterministic order
                    foreach (var f in files)
                    {
                        var s = LoadExternal("art/" + System.IO.Path.GetFileName(f), ppu);
                        if (s != null) _scenes.Add(s);
                    }
                }
            }
            catch { /* StreamingAssets not a real dir on some platforms — fall back to none */ }
            return _scenes;
        }

        /// Illustrated mid-ground clutter cutouts — every `art/mid_*.png`, loaded at `ppu`
        /// with a TOP-centre pivot so the builder can hang them from the ceiling band.
        /// Transparent PNGs (chroma-keyed + darkened). Empty list when none exist, so the
        /// builder falls back to its code-drawn silhouettes. Drop a new mid_*.png in and
        /// it is picked up on the next level build — no code change.
        static List<Sprite> _midClutter;
        public static List<Sprite> MidgroundClutter(float ppu)
        {
            if (_midClutter != null) return _midClutter;
            _midClutter = new List<Sprite>();
            try
            {
                string dir = System.IO.Path.Combine(Application.streamingAssetsPath, "art");
                if (System.IO.Directory.Exists(dir))
                {
                    var files = System.IO.Directory.GetFiles(dir, "mid_*.png");
                    System.Array.Sort(files);
                    foreach (var f in files)
                    {
                        var s = LoadExternal("art/" + System.IO.Path.GetFileName(f), ppu, new Vector2(0.5f, 1f));
                        if (s != null) _midClutter.Add(s);
                    }
                }
            }
            catch { /* fall back to code silhouettes */ }
            return _midClutter;
        }

        /// Soft lamp light cone (wide at the bottom, fading down).
        public static Sprite LightCone
        {
            get
            {
                if (_lightCone == null)
                {
                    int w = 96, h = 128;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float v = 1f - y / (float)h;             // 0 top (at the lamp) -> 1 bottom
                            float halfW = Mathf.Lerp(0.10f, 0.48f, v) * w;
                            float dx = Mathf.Abs(x - w / 2f);
                            float a = dx < halfW
                                ? Mathf.Pow(1f - dx / halfW, 1.4f) * Mathf.Pow(1f - v, 1.6f) * 0.55f
                                : 0f;
                            px[y * w + x] = new Color32(255, 244, 222, (byte)(a * 255f));
                        }
                    // texture row 0 is the BOTTOM: invert so the cone widens downward
                    var flipped = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                            flipped[y * w + x] = px[(h - 1 - y) * w + x];
                    tex.SetPixels32(flipped);
                    tex.Apply();
                    _lightCone = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 1f), 32f, 0, SpriteMeshType.FullRect);
                    _lightCone.name = "LightCone";
                }
                return _lightCone;
            }
        }

        static Sprite _lightBeam;
        /// A single natural volumetric beam: HOT at the source (top), a brighter
        /// inner core, gaussian-feathered (soft, not a hard cone), gently widening,
        /// fading smoothly to nothing along its length. Pivot top-centre so it
        /// emanates from the bulb. Replaces the old hard double-cone.
        public static Sprite LightBeam
        {
            get
            {
                if (_lightBeam == null)
                {
                    int w = 128, h = 200;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float ty = (h - 1 - y) / (float)(h - 1);              // 0 source (top) -> 1 far end
                            float halfW = Mathf.Lerp(0.07f, 0.40f, Mathf.Pow(ty, 0.8f)) * w;
                            float dx = Mathf.Abs(x - w / 2f) / halfW;
                            float soft = Mathf.Exp(-dx * dx * 2.1f);              // feathered body (no hard edge)
                            float core = Mathf.Exp(-dx * dx * 8.5f);              // tighter bright core streak
                            float vert = Mathf.Pow(1f - ty, 1.6f);               // fade down the length
                            float hot = Mathf.Exp(-ty * ty * 24f);               // bright hot-spot at the source
                            float a = (soft * 0.5f + core * 0.5f) * vert + hot * soft * 0.55f;
                            px[y * w + x] = new Color32(255, 244, 222, (byte)(Mathf.Clamp01(a) * 0.62f * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _lightBeam = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 1f), 44f, 0, SpriteMeshType.FullRect);
                    _lightBeam.name = "LightBeam";
                }
                return _lightBeam;
            }
        }

        static Sprite _edgeFade;
        /// Vertical gradient: opaque at the TOP, fading to transparent downward — a soft
        /// catch-light rim that bleeds a platform's lit lip down its face (a 3D-ledge cue).
        /// Pivot top-centre so it grows downward from the lip.
        public static Sprite EdgeFade
        {
            get
            {
                if (_edgeFade == null)
                {
                    // square + ppu==h so native size is exactly 1x1 world units (like
                    // WhiteSprite): a localScale of (s.x, rimH) then gives the right size.
                    // (An 8-wide texture at ppu 64 was only 0.125u native -> a thin streak.)
                    int w = 64, h = 64;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float ty = (h - 1 - y) / (float)(h - 1);   // 0 top -> 1 bottom
                            float a = Mathf.Pow(1f - ty, 2.2f);
                            px[y * w + x] = new Color32(255, 255, 255, (byte)(a * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _edgeFade = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 1f), h, 0, SpriteMeshType.FullRect);
                    _edgeFade.name = "EdgeFade";
                }
                return _edgeFade;
            }
        }

        /// Hanging lamp shade silhouette (truncated cone).
        public static Sprite ConeShade
        {
            get
            {
                if (_coneShade == null)
                {
                    int w = 48, h = 28;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float v = y / (float)h;                  // 0 bottom -> 1 top
                            float halfW = Mathf.Lerp(0.48f, 0.10f, v) * w;
                            float dx = Mathf.Abs(x - w / 2f);
                            bool inside = dx < halfW;
                            byte g = (byte)(inside ? (y < 3 ? 0x2E : 0x17) : 0);
                            px[y * w + x] = new Color32(g, g, (byte)(g + 2), (byte)(inside ? 255 : 0));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _coneShade = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 0f), 48f, 0, SpriteMeshType.FullRect);
                    _coneShade.name = "ConeShade";
                }
                return _coneShade;
            }
        }

        /// Stone blocks: grout lines + deterministic speckle.
        public static Sprite GroundTile
        {
            get
            {
                if (_ground == null)
                    _ground = MakeTile("GroundTile", 16, 16f, (x, y) =>
                    {
                        if (x == 0 || y == 0) return C(0x5F5F5F);
                        int n = (x * 7 + y * 13) % 7;
                        if (n == 0) return C(0x676767);
                        if (n == 3) return C(0x747474);
                        return C(0x6E6E6E);
                    });
                return _ground;
            }
        }

        /// Glowing cold-blue energy band: bright core line, soft vertical
        /// falloff. Drawn stretched (not tiled) — it is a gradient.
        public static Sprite DarkPathTile
        {
            get
            {
                if (_darkPath == null)
                {
                    int w = 16, h = 64;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    tex.wrapMode = TextureWrapMode.Repeat;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float dy = Mathf.Abs(y - h / 2f) / (h / 2f);
                            float core = Mathf.Pow(Mathf.Max(0f, 1f - dy), 2.4f);
                            var col = Color.Lerp(new Color(0.34f, 0.45f, 0.85f), new Color(0.86f, 0.92f, 1f), core);
                            px[y * w + x] = new Color32(
                                (byte)(col.r * 255f), (byte)(col.g * 255f), (byte)(col.b * 255f),
                                (byte)(Mathf.Clamp01(0.25f + core * 0.75f) * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _darkPath = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 0.5f), h, 0, SpriteMeshType.FullRect);
                    _darkPath.name = "DarkPathBand";
                }
                return _darkPath;
            }
        }

        /// Pale fog-glass panel: translucent vertical sheen (cinematic restyle).
        public static Sprite BarrierTile
        {
            get
            {
                if (_barrier == null)
                    _barrier = MakeTile("BarrierTile", 32, 32f, (x, y) =>
                    {
                        float sheen = 0.5f + 0.5f * Mathf.Sin(x * 0.7f);
                        float n = ValueNoise(x / 6f, y / 6f, 71);
                        byte a = (byte)(Mathf.Clamp01(0.72f + sheen * 0.18f + n * 0.08f) * 255f);
                        return new Color32(0xE9, 0xE9, 0xE6, a);
                    });
                return _barrier;
            }
        }

        /// Horizontal slats.
        public static Sprite DoorTile
        {
            get
            {
                if (_door == null)
                    _door = MakeTile("DoorTile", 48, 48f, (x, y) =>
                    {
                        if (y % 16 < 2) return C(0x4F4F4F);   // recessed slat shadow
                        if (x < 2) return C(0x575757);        // side bevel
                        return C(0x5E5E5E);
                    });
                return _door;
            }
        }

        // ---------- pickups ----------

        static Sprite _flash, _shutter, _exit;

        /// Glowing flash bulb on a small base.
        public static Sprite FlashPickup
        {
            get
            {
                if (_flash == null)
                    _flash = FromMap("FlashPickup", new[]
                    {
                        ".WWWWWW.",
                        "WWXXXXWW",
                        "WXXXXXXW",
                        "WXXXXXXW",
                        "WWXXXXWW",
                        ".WWWWWW.",
                        "...DD...",
                        "..DDDD..",
                    }, new Dictionary<char, Color32>
                    {
                        { 'W', C(0xFFF3D6) }, { 'X', C(0xFFFFFF) }, { 'D', C(0x8A8570) },
                    }, 16f);
                return _flash;
            }
        }

        /// Little camera with a cyan lens.
        public static Sprite ShutterPickup
        {
            get
            {
                if (_shutter == null)
                    _shutter = FromMap("ShutterPickup", new[]
                    {
                        "..TT....",
                        "CCCCCCCC",
                        "CCLLLLCC",
                        "CLLPPLLC",
                        "CLLPPLLC",
                        "CCLLLLCC",
                        "CCCCCCCC",
                        "........",
                    }, new Dictionary<char, Color32>
                    {
                        { 'C', C(0x3B3B3B) }, { 'L', C(0x9FD8E6) }, { 'P', C(0x1E2A33) }, { 'T', C(0x575757) },
                    }, 16f);
                return _shutter;
            }
        }

        static Sprite _disc, _softGlow;

        /// Anti-aliased filled circle (UI knobs, REC dot, lenses, bulbs).
        public static Sprite Disc
        {
            get
            {
                if (_disc == null)
                {
                    int n = 64;
                    var tex = new Texture2D(n, n, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[n * n];
                    for (int y = 0; y < n; y++)
                        for (int x = 0; x < n; x++)
                        {
                            float dx = (x + 0.5f - n / 2f) / (n / 2f);
                            float dy = (y + 0.5f - n / 2f) / (n / 2f);
                            float r = Mathf.Sqrt(dx * dx + dy * dy);
                            float a = Mathf.Clamp01((1f - r) * (n / 2f) * 0.5f);
                            px[y * n + x] = new Color32(255, 255, 255, (byte)(a * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _disc = Sprite.Create(tex, new Rect(0, 0, n, n), new Vector2(0.5f, 0.5f), n, 0, SpriteMeshType.FullRect);
                    _disc.name = "Disc";
                }
                return _disc;
            }
        }

        /// Soft radial falloff — halos, sparkles, light pools.
        public static Sprite SoftGlow
        {
            get
            {
                if (_softGlow == null)
                {
                    int n = 128;
                    var tex = new Texture2D(n, n, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[n * n];
                    for (int y = 0; y < n; y++)
                        for (int x = 0; x < n; x++)
                        {
                            float dx = (x + 0.5f - n / 2f) / (n / 2f);
                            float dy = (y + 0.5f - n / 2f) / (n / 2f);
                            float r = Mathf.Clamp01(Mathf.Sqrt(dx * dx + dy * dy));
                            float a = Mathf.Pow(1f - r, 2.2f);
                            px[y * n + x] = new Color32(255, 255, 255, (byte)(a * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _softGlow = Sprite.Create(tex, new Rect(0, 0, n, n), new Vector2(0.5f, 0.5f), n, 0, SpriteMeshType.FullRect);
                    _softGlow.name = "SoftGlow";
                }
                return _softGlow;
            }
        }

        static Sprite _negative;

        /// A strip of film negative: dark frame, sprocket notches, pale window.
        public static Sprite NegativePickup
        {
            get
            {
                if (_negative == null)
                    _negative = FromMap("NegativePickup", new[]
                    {
                        "NNNNNNNNNN",
                        "N.N.N.N.NN",
                        "NWWWWWWWWN",
                        "NWWWWWWWWN",
                        "NWWBBWWWWN",
                        "NWWWWWWWWN",
                        "NWWWWWWWWN",
                        "N.N.N.N.NN",
                        "NNNNNNNNNN",
                        "..........",
                    }, new Dictionary<char, Color32>
                    {
                        { 'N', C(0x2A2A30) }, { 'W', C(0x9FB4D8) }, { 'B', C(0x1A1E28) },
                    }, 18f);
                return _negative;
            }
        }

        static Sprite _cpMarker;

        /// Small hanging photo: checkpoint marker (brightens when developed).
        public static Sprite CheckpointMarker
        {
            get
            {
                if (_cpMarker == null)
                    _cpMarker = FromMap("CheckpointMarker", new[]
                    {
                        "..CC..",
                        "FFFFFF",
                        "FPPPPF",
                        "FPPPPF",
                        "FPPPPF",
                        "FPPPPF",
                        "FFFFFF",
                        "......",
                    }, new Dictionary<char, Color32>
                    {
                        { 'C', C(0x6A6A6A) }, { 'F', C(0x585858) }, { 'P', C(0x3A3A3A) },
                    }, 12f);
                return _cpMarker;
            }
        }

        /// Safelight-red exit door: frame, window, handle.
        public static Sprite ExitDoor
        {
            get
            {
                if (_exit == null)
                {
                    var rows = new string[20];
                    rows[0] = "FFFFFFFFFF";
                    rows[1] = "FRRRRRRRRF";
                    rows[2] = "FRRWWWWRRF";
                    rows[3] = "FRRWWWWRRF";
                    rows[4] = "FRRWWWWRRF";
                    for (int i = 5; i < 19; i++) rows[i] = "FRRRRRRRRF";
                    rows[10] = "FRRRRRRHRF";
                    rows[11] = "FRRRRRRHRF";
                    rows[19] = "FFFFFFFFFF";
                    _exit = FromMap("ExitDoor", rows, new Dictionary<char, Color32>
                    {
                        { 'F', C(0xB03A2E) }, { 'R', C(0x8B1A1A) }, { 'W', C(0xF2D8D8) }, { 'H', C(0xFFF3D6) },
                    }, 10f);
                }
                return _exit;
            }
        }
    }
}
