using System.Collections.Generic;
using UnityEngine;

namespace Darkroom
{
    /// Procedural pixel art — sprites authored as string maps, world tiles
    /// generated by rule. Still zero external assets.
    public static class PixelArt
    {
        /// rows are listed top to bottom; '.' = transparent.
        public static Sprite FromMap(string name, string[] rows, Dictionary<char, Color32> palette, float ppu)
        {
            int h = rows.Length, w = rows[0].Length;
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
            tex.filterMode = FilterMode.Point;
            var px = new Color32[w * h];
            for (int y = 0; y < h; y++)
                for (int x = 0; x < w; x++)
                {
                    char c = rows[y][x];
                    px[(h - 1 - y) * w + x] = c == '.' ? new Color32(0, 0, 0, 0) : palette[c];
                }
            tex.SetPixels32(px);
            tex.Apply();
            var s = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 0.5f), ppu, 0, SpriteMeshType.FullRect);
            s.name = name;
            return s;
        }

        static Sprite MakeTile(string name, int size, float ppu, System.Func<int, int, Color32> pixel)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            tex.filterMode = FilterMode.Point;
            tex.wrapMode = TextureWrapMode.Repeat;
            var px = new Color32[size * size];
            for (int y = 0; y < size; y++)
                for (int x = 0; x < size; x++)
                    px[y * size + x] = pixel(x, y);
            tex.SetPixels32(px);
            tex.Apply();
            var s = Sprite.Create(tex, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), ppu, 0, SpriteMeshType.FullRect);
            s.name = name;
            return s;
        }

        static Color32 C(int rgb) =>
            new Color32((byte)((rgb >> 16) & 0xFF), (byte)((rgb >> 8) & 0xFF), (byte)(rgb & 0xFF), 255);

        // ---------- world tiles (one tile = one world unit) ----------

        static Sprite _ground, _darkPath, _barrier, _door;

        /// Stone blocks: grout lines + deterministic speckle.
        public static Sprite GroundTile
        {
            get
            {
                if (_ground == null)
                    _ground = MakeTile("GroundTile", 16, 16f, (x, y) =>
                    {
                        if (x == 0 || y == 0) return C(0x5F5F5F);
                        int n = (x * 7 + y * 13) % 7;
                        if (n == 0) return C(0x676767);
                        if (n == 3) return C(0x747474);
                        return C(0x6E6E6E);
                    });
                return _ground;
            }
        }

        /// Deep blue with scattered star pixels.
        public static Sprite DarkPathTile
        {
            get
            {
                if (_darkPath == null)
                    _darkPath = MakeTile("DarkPathTile", 12, 12f, (x, y) =>
                    {
                        int n = (x * 5 + y * 3) % 17;
                        if (n == 0) return C(0x7B92D8);
                        if (n == 9) return C(0x2F3D74);
                        return C(0x3A4A8C);
                    });
                return _darkPath;
            }
        }

        /// Near-white with vertical light streaks.
        public static Sprite BarrierTile
        {
            get
            {
                if (_barrier == null)
                    _barrier = MakeTile("BarrierTile", 12, 12f, (x, y) =>
                    {
                        if (x % 4 == 1) return C(0xFBFBFB);
                        if (x % 4 == 3) return C(0xE0E0E0);
                        return C(0xEDEDED);
                    });
                return _barrier;
            }
        }

        /// Horizontal slats.
        public static Sprite DoorTile
        {
            get
            {
                if (_door == null)
                    _door = MakeTile("DoorTile", 12, 12f, (x, y) =>
                    {
                        if (y % 4 == 0) return C(0x4F4F4F);
                        if (x == 0) return C(0x575757);
                        return C(0x5E5E5E);
                    });
                return _door;
            }
        }

        // ---------- pickups ----------

        static Sprite _flash, _shutter, _exit;

        /// Glowing flash bulb on a small base.
        public static Sprite FlashPickup
        {
            get
            {
                if (_flash == null)
                    _flash = FromMap("FlashPickup", new[]
                    {
                        ".WWWWWW.",
                        "WWXXXXWW",
                        "WXXXXXXW",
                        "WXXXXXXW",
                        "WWXXXXWW",
                        ".WWWWWW.",
                        "...DD...",
                        "..DDDD..",
                    }, new Dictionary<char, Color32>
                    {
                        { 'W', C(0xFFF3D6) }, { 'X', C(0xFFFFFF) }, { 'D', C(0x8A8570) },
                    }, 16f);
                return _flash;
            }
        }

        /// Little camera with a cyan lens.
        public static Sprite ShutterPickup
        {
            get
            {
                if (_shutter == null)
                    _shutter = FromMap("ShutterPickup", new[]
                    {
                        "..TT....",
                        "CCCCCCCC",
                        "CCLLLLCC",
                        "CLLPPLLC",
                        "CLLPPLLC",
                        "CCLLLLCC",
                        "CCCCCCCC",
                        "........",
                    }, new Dictionary<char, Color32>
                    {
                        { 'C', C(0x3B3B3B) }, { 'L', C(0x9FD8E6) }, { 'P', C(0x1E2A33) }, { 'T', C(0x575757) },
                    }, 16f);
                return _shutter;
            }
        }

        static Sprite _cpMarker;

        /// Small hanging photo: checkpoint marker (brightens when developed).
        public static Sprite CheckpointMarker
        {
            get
            {
                if (_cpMarker == null)
                    _cpMarker = FromMap("CheckpointMarker", new[]
                    {
                        "..CC..",
                        "FFFFFF",
                        "FPPPPF",
                        "FPPPPF",
                        "FPPPPF",
                        "FPPPPF",
                        "FFFFFF",
                        "......",
                    }, new Dictionary<char, Color32>
                    {
                        { 'C', C(0x6A6A6A) }, { 'F', C(0x585858) }, { 'P', C(0x3A3A3A) },
                    }, 12f);
                return _cpMarker;
            }
        }

        /// Safelight-red exit door: frame, window, handle.
        public static Sprite ExitDoor
        {
            get
            {
                if (_exit == null)
                {
                    var rows = new string[20];
                    rows[0] = "FFFFFFFFFF";
                    rows[1] = "FRRRRRRRRF";
                    rows[2] = "FRRWWWWRRF";
                    rows[3] = "FRRWWWWRRF";
                    rows[4] = "FRRWWWWRRF";
                    for (int i = 5; i < 19; i++) rows[i] = "FRRRRRRRRF";
                    rows[10] = "FRRRRRRHRF";
                    rows[11] = "FRRRRRRHRF";
                    rows[19] = "FFFFFFFFFF";
                    _exit = FromMap("ExitDoor", rows, new Dictionary<char, Color32>
                    {
                        { 'F', C(0xB03A2E) }, { 'R', C(0x8B1A1A) }, { 'W', C(0xF2D8D8) }, { 'H', C(0xFFF3D6) },
                    }, 10f);
                }
                return _exit;
            }
        }
    }
}
