using System.Collections.Generic;
using UnityEngine;

namespace Darkroom
{
    /// Procedural pixel art — sprites authored as string maps, world tiles
    /// generated by rule. Still zero external assets.
    public static class PixelArt
    {
        /// rows are listed top to bottom; '.' = transparent.
        public static Sprite FromMap(string name, string[] rows, Dictionary<char, Color32> palette, float ppu)
        {
            int h = rows.Length, w = rows[0].Length;
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
            tex.filterMode = FilterMode.Point;
            var px = new Color32[w * h];
            for (int y = 0; y < h; y++)
                for (int x = 0; x < w; x++)
                {
                    char c = rows[y][x];
                    px[(h - 1 - y) * w + x] = c == '.' ? new Color32(0, 0, 0, 0) : palette[c];
                }
            tex.SetPixels32(px);
            tex.Apply();
            var s = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 0.5f), ppu, 0, SpriteMeshType.FullRect);
            s.name = name;
            return s;
        }

        static Sprite MakeTile(string name, int size, float ppu, System.Func<int, int, Color32> pixel)
        {
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);
            tex.filterMode = FilterMode.Point;
            tex.wrapMode = TextureWrapMode.Repeat;
            var px = new Color32[size * size];
            for (int y = 0; y < size; y++)
                for (int x = 0; x < size; x++)
                    px[y * size + x] = pixel(x, y);
            tex.SetPixels32(px);
            tex.Apply();
            var s = Sprite.Create(tex, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), ppu, 0, SpriteMeshType.FullRect);
            s.name = name;
            return s;
        }

        static Color32 C(int rgb) =>
            new Color32((byte)((rgb >> 16) & 0xFF), (byte)((rgb >> 8) & 0xFF), (byte)(rgb & 0xFF), 255);

        // ---------- noise ----------

        static float Hash(int x, int y, int s)
        {
            unchecked
            {
                int h = x * 374761393 + y * 668265263 + s * 1442695041;
                h = (h ^ (h >> 13)) * 1274126177;
                return ((h ^ (h >> 16)) & 0x7FFFFFFF) / (float)int.MaxValue;
            }
        }

        static float ValueNoise(float x, float y, int seed)
        {
            int x0 = Mathf.FloorToInt(x), y0 = Mathf.FloorToInt(y);
            float fx = x - x0, fy = y - y0;
            float a = Hash(x0, y0, seed), b = Hash(x0 + 1, y0, seed);
            float c = Hash(x0, y0 + 1, seed), d = Hash(x0 + 1, y0 + 1, seed);
            return Mathf.Lerp(Mathf.Lerp(a, b, fx), Mathf.Lerp(c, d, fx), fy);
        }

        // ---------- world tiles (one tile = one world unit) ----------

        static Sprite _ground, _darkPath, _barrier, _door;
        static Sprite _concrete, _brick, _lightCone, _coneShade;

        /// Dark concrete with grime (cinematic restyle).
        public static Sprite ConcreteTile
        {
            get
            {
                if (_concrete == null)
                    _concrete = MakeTile("ConcreteTile", 64, 64f, (x, y) =>
                    {
                        float n = ValueNoise(x / 8f, y / 8f, 11) * 0.6f + ValueNoise(x / 3f, y / 3f, 23) * 0.4f;
                        float v = 0.075f + n * 0.035f;
                        if (ValueNoise(x / 16f, y / 5f, 37) > 0.88f) v *= 0.7f; // grime streaks
                        byte g = (byte)(v * 255f);
                        return new Color32(g, g, (byte)(g + 3), 255);
                    });
                return _concrete;
            }
        }

        /// Very dark brick wall with mortar lines.
        public static Sprite BrickTile
        {
            get
            {
                if (_brick == null)
                    _brick = MakeTile("BrickTile", 64, 64f, (x, y) =>
                    {
                        int row = y / 16;
                        int xo = (row % 2) * 16;
                        bool mortar = (y % 16) < 2 || ((x + xo) % 32) < 2;
                        if (mortar) return new Color32(0x0A, 0x0A, 0x0C, 255);
                        float n = ValueNoise(x / 5f, y / 5f, 51);
                        byte g = (byte)((0.085f + n * 0.03f) * 255f);
                        return new Color32(g, g, (byte)(g + 2), 255);
                    });
                return _brick;
            }
        }

        /// Soft lamp light cone (wide at the bottom, fading down).
        public static Sprite LightCone
        {
            get
            {
                if (_lightCone == null)
                {
                    int w = 96, h = 128;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float v = 1f - y / (float)h;             // 0 top (at the lamp) -> 1 bottom
                            float halfW = Mathf.Lerp(0.10f, 0.48f, v) * w;
                            float dx = Mathf.Abs(x - w / 2f);
                            float a = dx < halfW
                                ? Mathf.Pow(1f - dx / halfW, 1.4f) * Mathf.Pow(1f - v, 1.6f) * 0.55f
                                : 0f;
                            px[y * w + x] = new Color32(255, 244, 222, (byte)(a * 255f));
                        }
                    // texture row 0 is the BOTTOM: invert so the cone widens downward
                    var flipped = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                            flipped[y * w + x] = px[(h - 1 - y) * w + x];
                    tex.SetPixels32(flipped);
                    tex.Apply();
                    _lightCone = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 1f), 32f, 0, SpriteMeshType.FullRect);
                    _lightCone.name = "LightCone";
                }
                return _lightCone;
            }
        }

        /// Hanging lamp shade silhouette (truncated cone).
        public static Sprite ConeShade
        {
            get
            {
                if (_coneShade == null)
                {
                    int w = 48, h = 28;
                    var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[w * h];
                    for (int y = 0; y < h; y++)
                        for (int x = 0; x < w; x++)
                        {
                            float v = y / (float)h;                  // 0 bottom -> 1 top
                            float halfW = Mathf.Lerp(0.48f, 0.10f, v) * w;
                            float dx = Mathf.Abs(x - w / 2f);
                            bool inside = dx < halfW;
                            byte g = (byte)(inside ? (y < 3 ? 0x2E : 0x17) : 0);
                            px[y * w + x] = new Color32(g, g, (byte)(g + 2), (byte)(inside ? 255 : 0));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _coneShade = Sprite.Create(tex, new Rect(0, 0, w, h), new Vector2(0.5f, 0f), 48f, 0, SpriteMeshType.FullRect);
                    _coneShade.name = "ConeShade";
                }
                return _coneShade;
            }
        }

        /// Stone blocks: grout lines + deterministic speckle.
        public static Sprite GroundTile
        {
            get
            {
                if (_ground == null)
                    _ground = MakeTile("GroundTile", 16, 16f, (x, y) =>
                    {
                        if (x == 0 || y == 0) return C(0x5F5F5F);
                        int n = (x * 7 + y * 13) % 7;
                        if (n == 0) return C(0x676767);
                        if (n == 3) return C(0x747474);
                        return C(0x6E6E6E);
                    });
                return _ground;
            }
        }

        /// Deep blue with scattered star pixels.
        public static Sprite DarkPathTile
        {
            get
            {
                if (_darkPath == null)
                    _darkPath = MakeTile("DarkPathTile", 12, 12f, (x, y) =>
                    {
                        int n = (x * 5 + y * 3) % 17;
                        if (n == 0) return C(0x7B92D8);
                        if (n == 9) return C(0x2F3D74);
                        return C(0x3A4A8C);
                    });
                return _darkPath;
            }
        }

        /// Pale fog-glass panel: translucent vertical sheen (cinematic restyle).
        public static Sprite BarrierTile
        {
            get
            {
                if (_barrier == null)
                    _barrier = MakeTile("BarrierTile", 32, 32f, (x, y) =>
                    {
                        float sheen = 0.5f + 0.5f * Mathf.Sin(x * 0.7f);
                        float n = ValueNoise(x / 6f, y / 6f, 71);
                        byte a = (byte)(Mathf.Clamp01(0.72f + sheen * 0.18f + n * 0.08f) * 255f);
                        return new Color32(0xE9, 0xE9, 0xE6, a);
                    });
                return _barrier;
            }
        }

        /// Horizontal slats.
        public static Sprite DoorTile
        {
            get
            {
                if (_door == null)
                    _door = MakeTile("DoorTile", 12, 12f, (x, y) =>
                    {
                        if (y % 4 == 0) return C(0x4F4F4F);
                        if (x == 0) return C(0x575757);
                        return C(0x5E5E5E);
                    });
                return _door;
            }
        }

        // ---------- pickups ----------

        static Sprite _flash, _shutter, _exit;

        /// Glowing flash bulb on a small base.
        public static Sprite FlashPickup
        {
            get
            {
                if (_flash == null)
                    _flash = FromMap("FlashPickup", new[]
                    {
                        ".WWWWWW.",
                        "WWXXXXWW",
                        "WXXXXXXW",
                        "WXXXXXXW",
                        "WWXXXXWW",
                        ".WWWWWW.",
                        "...DD...",
                        "..DDDD..",
                    }, new Dictionary<char, Color32>
                    {
                        { 'W', C(0xFFF3D6) }, { 'X', C(0xFFFFFF) }, { 'D', C(0x8A8570) },
                    }, 16f);
                return _flash;
            }
        }

        /// Little camera with a cyan lens.
        public static Sprite ShutterPickup
        {
            get
            {
                if (_shutter == null)
                    _shutter = FromMap("ShutterPickup", new[]
                    {
                        "..TT....",
                        "CCCCCCCC",
                        "CCLLLLCC",
                        "CLLPPLLC",
                        "CLLPPLLC",
                        "CCLLLLCC",
                        "CCCCCCCC",
                        "........",
                    }, new Dictionary<char, Color32>
                    {
                        { 'C', C(0x3B3B3B) }, { 'L', C(0x9FD8E6) }, { 'P', C(0x1E2A33) }, { 'T', C(0x575757) },
                    }, 16f);
                return _shutter;
            }
        }

        static Sprite _disc, _softGlow;

        /// Anti-aliased filled circle (UI knobs, REC dot, lenses, bulbs).
        public static Sprite Disc
        {
            get
            {
                if (_disc == null)
                {
                    int n = 64;
                    var tex = new Texture2D(n, n, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[n * n];
                    for (int y = 0; y < n; y++)
                        for (int x = 0; x < n; x++)
                        {
                            float dx = (x + 0.5f - n / 2f) / (n / 2f);
                            float dy = (y + 0.5f - n / 2f) / (n / 2f);
                            float r = Mathf.Sqrt(dx * dx + dy * dy);
                            float a = Mathf.Clamp01((1f - r) * (n / 2f) * 0.5f);
                            px[y * n + x] = new Color32(255, 255, 255, (byte)(a * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _disc = Sprite.Create(tex, new Rect(0, 0, n, n), new Vector2(0.5f, 0.5f), n, 0, SpriteMeshType.FullRect);
                    _disc.name = "Disc";
                }
                return _disc;
            }
        }

        /// Soft radial falloff — halos, sparkles, light pools.
        public static Sprite SoftGlow
        {
            get
            {
                if (_softGlow == null)
                {
                    int n = 128;
                    var tex = new Texture2D(n, n, TextureFormat.RGBA32, false);
                    tex.filterMode = FilterMode.Bilinear;
                    var px = new Color32[n * n];
                    for (int y = 0; y < n; y++)
                        for (int x = 0; x < n; x++)
                        {
                            float dx = (x + 0.5f - n / 2f) / (n / 2f);
                            float dy = (y + 0.5f - n / 2f) / (n / 2f);
                            float r = Mathf.Clamp01(Mathf.Sqrt(dx * dx + dy * dy));
                            float a = Mathf.Pow(1f - r, 2.2f);
                            px[y * n + x] = new Color32(255, 255, 255, (byte)(a * 255f));
                        }
                    tex.SetPixels32(px);
                    tex.Apply();
                    _softGlow = Sprite.Create(tex, new Rect(0, 0, n, n), new Vector2(0.5f, 0.5f), n, 0, SpriteMeshType.FullRect);
                    _softGlow.name = "SoftGlow";
                }
                return _softGlow;
            }
        }

        static Sprite _negative;

        /// A strip of film negative: dark frame, sprocket notches, pale window.
        public static Sprite NegativePickup
        {
            get
            {
                if (_negative == null)
                    _negative = FromMap("NegativePickup", new[]
                    {
                        "NNNNNNNNNN",
                        "N.N.N.N.NN",
                        "NWWWWWWWWN",
                        "NWWWWWWWWN",
                        "NWWBBWWWWN",
                        "NWWWWWWWWN",
                        "NWWWWWWWWN",
                        "N.N.N.N.NN",
                        "NNNNNNNNNN",
                        "..........",
                    }, new Dictionary<char, Color32>
                    {
                        { 'N', C(0x2A2A30) }, { 'W', C(0x9FB4D8) }, { 'B', C(0x1A1E28) },
                    }, 18f);
                return _negative;
            }
        }

        static Sprite _cpMarker;

        /// Small hanging photo: checkpoint marker (brightens when developed).
        public static Sprite CheckpointMarker
        {
            get
            {
                if (_cpMarker == null)
                    _cpMarker = FromMap("CheckpointMarker", new[]
                    {
                        "..CC..",
                        "FFFFFF",
                        "FPPPPF",
                        "FPPPPF",
                        "FPPPPF",
                        "FPPPPF",
                        "FFFFFF",
                        "......",
                    }, new Dictionary<char, Color32>
                    {
                        { 'C', C(0x6A6A6A) }, { 'F', C(0x585858) }, { 'P', C(0x3A3A3A) },
                    }, 12f);
                return _cpMarker;
            }
        }

        /// Safelight-red exit door: frame, window, handle.
        public static Sprite ExitDoor
        {
            get
            {
                if (_exit == null)
                {
                    var rows = new string[20];
                    rows[0] = "FFFFFFFFFF";
                    rows[1] = "FRRRRRRRRF";
                    rows[2] = "FRRWWWWRRF";
                    rows[3] = "FRRWWWWRRF";
                    rows[4] = "FRRWWWWRRF";
                    for (int i = 5; i < 19; i++) rows[i] = "FRRRRRRRRF";
                    rows[10] = "FRRRRRRHRF";
                    rows[11] = "FRRRRRRHRF";
                    rows[19] = "FFFFFFFFFF";
                    _exit = FromMap("ExitDoor", rows, new Dictionary<char, Color32>
                    {
                        { 'F', C(0xB03A2E) }, { 'R', C(0x8B1A1A) }, { 'W', C(0xF2D8D8) }, { 'H', C(0xFFF3D6) },
                    }, 10f);
                }
                return _exit;
            }
        }
    }
}
